export const langMap: Record<string, string> = {
	af: "afrikaans",
	sq: "albanian",
	am: "amharic",
	ar: "arabic",
	hy: "armenian",
	az: "azerbaijani",
	eu: "basque",
	be: "belarusian",
	by: "belarusian",
	bn: "bengali",
	bs: "bosnian",
	bg: "bulgarian",
	ca: "catalan",
	ceb: "cebuano",
	ny: "chichewa",
	zh: "chinese",
	"zh-cn": "chinese",
	"zh-tw": "chinese",
	co: "corsican",
	hr: "croatian",
	cs: "czech",
	da: "danish",
	nl: "dutch",
	en: "english",
	en_us: "english",
	pi: "english pirate",
	eo: "esperanto",
	et: "estonian",
	tl: "tagalog",
	fi: "finnish",
	fr: "french",
	fy: "frisian",
	gl: "galician",
	ka: "georgian",
	de: "german",
	el: "greek",
	gu: "gujarati",
	ht: "haitian",
	ha: "hausa",
	haw: "hawaiian",
	he: "hebrew",
	iw: "hebrew",
	hi: "hindi",
	hmn: "mongolian",
	hu: "hungarian",
	is: "icelandic",
	ig: "igbo",
	id: "indonesian",
	ga: "irish",
	it: "italian",
	ja: "japanese",
	jw: "javanese",
	kn: "kannada",
	kk: "kazakh",
	km: "khmer",
	ko: "korean",
	ku: "kurdish",
	ky: "kyrgyz",
	lo: "lao",
	la: "latin",
	lv: "latvian",
	lt: "lithuanian",
	lb: "luxembourgish",
	mk: "macedonian",
	mg: "malagasy",
	ms: "malay",
	ml: "malayalam",
	mt: "maltese",
	mi: "maori",
	mr: "marathi",
	mn: "mongolian",
	my: "burmese",
	ne: "nepali",
	no: "norwegian",
	ps: "pashto",
	fa: "persian",
	pl: "polish",
	pt: "portuguese",
	"pt-br": "portuguese",
	pa: "punjabi",
	ro: "romanian",
	ru: "russian",
	sm: "samoan",
	gd: "gaelic scottish",
	sr: "serbian",
	st: "sotho southern",
	sn: "shona",
	sd: "sindhi",
	si: "sinhalese",
	si_lk: "sinhalese",
	sk: "slovak",
	sl: "slovene",
	so: "somali",
	es: "spanish",
	su: "sundanese",
	sw: "swahili",
	sv: "swedish",
	tg: "tajik",
	ta: "tamil",
	te: "telugu",
	th: "thai",
	tr: "turkish",
	uk: "ukrainian",
	ur: "urdu",
	uz: "uzbek",
	vi: "vietnamese",
	cy: "welsh",
	xh: "xhosa",
	yi: "yiddish",
	yo: "yoruba",
	zu: "zulu",
};

export function resolveDiscordLocaleLanguage(locale?: string | null) {
	const normalizedLocale = (locale || "en-US")
		.trim()
		.replaceAll("_", "-")
		.toLowerCase();
	const languageCode = normalizedLocale.split("-")[0];

	return langMap[normalizedLocale] || langMap[languageCode] || "english";
}
