import {
	InteractionFlags,
	ModalBuilder,
	LabelBuilder,
	TextInputBuilder,
	TextInputStyle,
} from "@minesa-org/mini-interaction";
import type {
	InteractionComponent,
	MessageComponentInteraction,
	StringSelectInteraction,
} from "@minesa-org/mini-interaction";
import {
	PUNISH_MESSAGE_CUSTOM_REASON_MODAL_ID,
	PUNISH_MESSAGE_CUSTOM_REASON_VALUE,
	PUNISH_MESSAGE_REASON_SELECT_ID,
	getPendingMessagePunishment,
	punishFlaggedMessage,
} from "../../commands/punish-message.ts";
import { buildPunishmentFailureContainer, findPreparedReason, getPunishmentConfig } from "../../utils/punishment.ts";
import { getEmoji } from "../../utils/index.ts";

const expiredReply = (interaction: StringSelectInteraction & MessageComponentInteraction) =>
	interaction.reply({
		content: `${getEmoji("error")} This request expired. Right-click the message again.`,
		flags: InteractionFlags.Ephemeral,
	});

const punishMessageReasonSelect: InteractionComponent = {
	customId: PUNISH_MESSAGE_REASON_SELECT_ID,

	handler: async (interaction) => {
		const selectInteraction = interaction as StringSelectInteraction &
			MessageComponentInteraction;
		const moderatorId = selectInteraction.user?.id ?? selectInteraction.member?.user?.id;
		const selected = selectInteraction.values?.[0];

		if (!moderatorId || !selected) {
			return selectInteraction.reply({
				content: `${getEmoji("error")} Could not read that selection.`,
				flags: InteractionFlags.Ephemeral,
			});
		}

		const pending = await getPendingMessagePunishment(moderatorId);
		if (!pending) return expiredReply(selectInteraction);

		if (selected === PUNISH_MESSAGE_CUSTOM_REASON_VALUE) {
			return selectInteraction.showModal(
				new ModalBuilder()
					.setCustomId(PUNISH_MESSAGE_CUSTOM_REASON_MODAL_ID)
					.setTitle("Custom punishment reason")
					.addComponents(
						new LabelBuilder()
							.setLabel("Reason")
							.setDescription(
								`Punishing <@${pending.targetUserId}> — keep it short and factual`,
							)
							.setComponent(
								new TextInputBuilder()
									.setCustomId("punishment:custom_reason")
									.setPlaceholder("Repeated mention spamming in #general")
									.setStyle(TextInputStyle.Paragraph)
									.setMaxLength(400)
									.setRequired(true),
							),
					),
			);
		}

		await selectInteraction.deferReply({
			flags: [InteractionFlags.Ephemeral, InteractionFlags.IsComponentsV2],
		});

		const config = await getPunishmentConfig(pending.guildId);
		const prepared = findPreparedReason(config, selected);

		if (!prepared) {
			return selectInteraction.editReply({
				components: [
					buildPunishmentFailureContainer({
						targetUserId: pending.targetUserId,
						reason: selected,
						error:
							"That reason no longer exists — the rules were probably re-generated by `/punishment setup`.",
					}),
				],
			});
		}

		await punishFlaggedMessage({
			moderatorId,
			reason: prepared.detail ? `${prepared.title} — ${prepared.detail}` : prepared.title,
			reasonId: prepared.id,
			interaction: selectInteraction,
		});
	},
};

export default punishMessageReasonSelect;
